// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SirecApi.Data;

#nullable disable

namespace SirecApi.Migrations
{
    [DbContext(typeof(SirecDbContext))]
    partial class SirecDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SirecApi.Models.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Colonia")
                        .HasColumnType("text");

                    b.Property<double>("ConfianzaCategoria")
                        .HasColumnType("double precision");

                    b.Property<double>("ConfianzaUrgencia")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereRevision")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Estado");

                    b.HasIndex("Urgencia");

                    b.ToTable("reportes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
